.TH __SPOT_CLASS 1 2025-9月 "" "Create spot class annotation"
.SH NAME
__spot_class \- __spot_class(cell.layers,
    <i>color</i> = <span style='color: brown;'><strong>'paper'</strong></span>)
.SH SYNOPSIS
\fI__spot_class(cell.layers,
    <i>color</i> = <span style='color: brown;'><strong>'paper'</strong></span>)\fR
.SH OPTIONS
.PP
\fBcell.layers\fB \fR\- . 
.PP
.PP
\fBcolor\fB \fR\- 'paper'. 
.PP
.SH DETAILS
.PP
use the max value column index as the cell class label
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__spot_class at deconv_matrix.R:line 77
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
