.TH __SPOT_CLASS 1 2024-Feb "" "Create spot class annotation"
.SH NAME
__spot_class \- __spot_class(cell.layers,
    <i>color</i> = paper)
.SH SYNOPSIS
\fI__spot_class(cell.layers,
    <i>color</i> = paper)\fR
.SH OPTIONS
.PP
\fBcell.layers\fB \fR\- . 
.PP
.PP
\fBcolor\fB \fR\- paper. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__spot_class at deconv_matrix.R:line 63
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
