.TH HUMAN_GENES.ANNOTATIONS 1 2025-Oct "" "human_genes.annotations"
.SH NAME
human_genes.annotations \- human_genes.annotations(
    <i>human.genes</i> = <span style='color: blue !important;'>NULL</span>,
    <i>index</i> = <span style='color: brown;'><strong>'Bgee'</strong></span>)
.SH SYNOPSIS
\fIhuman_genes.annotations(
    <i>human.genes</i> = <span style='color: blue !important;'>NULL</span>,
    <i>index</i> = <span style='color: brown;'><strong>'Bgee'</strong></span>)\fR
.SH OPTIONS
.PP
\fBhuman.genes\fB \fR\- NULL. 
.PP
.PP
\fBindex\fB \fR\- 'Bgee'. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.human_genes.annotations at uniprot.R:line 10
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
