.TH PLOT_PIE 1 2024-Jan "" "Plot the scatter pie data Display the cell distribution"
.SH NAME
plot_pie \- plot_pie(cell.layers)
.SH SYNOPSIS
\fIplot_pie(cell.layers)\fR
.SH OPTIONS
.PP
\fBcell.layers\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.plot_pie at pie.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
