.TH PLOT_CLASS 1 2023-Oct "" "plot spot class map"
.SH NAME
plot_class \- plot_class(spots.class,
    <i>colors</i> = paper)
.SH SYNOPSIS
\fIplot_class(spots.class,
    <i>colors</i> = paper)\fR
.SH OPTIONS
.PP
\fBspots.class\fB \fR\- . 
.PP
.PP
\fBcolors\fB \fR\- paper. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.plot_class at class.R:line 9
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
