.TH PLOT_VELOCITY 1 2025-Dec "" "plot single cells RNA velocity scatter"
.SH NAME
plot_velocity \- plot_velocity(x, y, vx, vy, class)
.SH SYNOPSIS
\fIplot_velocity(x, y, vx, vy, class)\fR
.SH OPTIONS
.PP
\fBx\fB \fR\- . the x dimension value of single cell embedding result
.PP
.PP
\fBy\fB \fR\- . the y dimension value of single cell embedding result
.PP
.PP
\fBvx\fB \fR\- . the dimension x of the velocity embedding result
.PP
.PP
\fBvy\fB \fR\- . the dimension y of the velocity embedding result
.PP
.PP
\fBclass\fB \fR\- . the cluster label of each corresponding single cells
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.plot_velocity at plot_velocity.R:line 10
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
