.TH PLOT_CLASS 1 2026-Jan "" "plot spot class map"
.SH NAME
plot_class \- plot_class(spots.class,
    <i>colors</i> = <span style='color: brown;'><strong>'paper'</strong></span>,
    <i>title</i> = <span style='color: brown;'><strong>'Spatial Spot Class'</strong></span>,
    <i>padding</i> = <span style='color: brown;'><strong>'padding: 150px 350px 200px 200px;'</strong></span>)
.SH SYNOPSIS
\fIplot_class(spots.class,
    <i>colors</i> = <span style='color: brown;'><strong>'paper'</strong></span>,
    <i>title</i> = <span style='color: brown;'><strong>'Spatial Spot Class'</strong></span>,
    <i>padding</i> = <span style='color: brown;'><strong>'padding: 150px 350px 200px 200px;'</strong></span>)\fR
.SH OPTIONS
.PP
\fBspots.class\fB \fR\- . 
.PP
.PP
\fBcolors\fB \fR\- 'paper'. 
.PP
.PP
\fBtitle\fB \fR\- 'Spatial Spot Class'. 
.PP
.PP
\fBpadding\fB \fR\- 'padding: 150px 350px 200px 200px;'. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.plot_class at class.R:line 9
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2026
