.TH SINGLE_NMF 1 2025-Jul "" "Non-negative Matrix Factorization (NMF) on single cells data"
.SH NAME
single_nmf \- single_nmf(x,
    <i>dims</i> = <span style='color: green;'>9</span>,
    <i>max.iters</i> = <span style='color: green;'>1000</span>,
    <i>n.threads</i> = <span style='color: green;'>8</span>)
.SH SYNOPSIS
\fIsingle_nmf(x,
    <i>dims</i> = <span style='color: green;'>9</span>,
    <i>max.iters</i> = <span style='color: green;'>1000</span>,
    <i>n.threads</i> = <span style='color: green;'>8</span>)\fR
.SH OPTIONS
.PP
\fBx\fB \fR\- . 
.PP
.PP
\fBdims\fB \fR\- 9. 
.PP
.PP
\fBmax.iters\fB \fR\- 1000. 
.PP
.PP
\fBn.threads\fB \fR\- 8. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.single_nmf at nmf.R:line 49
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
