.TH VAE_EMBEDDING 1 2025-Jun "" "create single cell matrix embedding via VAE"
.SH NAME
vae_embedding \- vae_embedding(x,
    <i>dims</i> = <span style='color: green;'>9</span>,
    <i>batch.size</i> = <span style='color: green;'>100</span>,
    <i>iterations</i> = <span style='color: green;'>1000</span>)
.SH SYNOPSIS
\fIvae_embedding(x,
    <i>dims</i> = <span style='color: green;'>9</span>,
    <i>batch.size</i> = <span style='color: green;'>100</span>,
    <i>iterations</i> = <span style='color: green;'>1000</span>)\fR
.SH OPTIONS
.PP
\fBx\fB \fR\- . 
.PP
.PP
\fBdims\fB \fR\- 9. the embedding dimension size
.PP
.PP
\fBbatch.size\fB \fR\- 100. 
.PP
.PP
\fBiterations\fB \fR\- 1000. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.vae_embedding at VAE.R:line 6
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
