.\" man page create by R# package system.
.TH BGEE 1 2000-1月 "development_stage" "development_stage"
.SH NAME
development_stage \- get all development stage information from the bgee dataset
.SH SYNOPSIS
\fIdevelopment_stage(\fBbgee\fR as <generic> BgeeDiskReader);\fR
.SH DESCRIPTION
.PP
get all development stage information from the bgee dataset
.PP
.SH OPTIONS
.PP
\fBbgee\fB \fR\- -. 
.PP
.SH SEE ALSO
Bgee
.SH FILES
.PP
Erica.dll
.PP
