.\" man page create by R# package system.
.TH BGEE 1 2000-1月 "geneIDs" "geneIDs"
.SH NAME
geneIDs \- get all gene ids from the bgee dataset
.SH SYNOPSIS
\fIgeneIDs(\fBbgee\fR as <generic> BgeeDiskReader);\fR
.SH DESCRIPTION
.PP
get all gene ids from the bgee dataset
.PP
.SH OPTIONS
.PP
\fBbgee\fB \fR\- -. 
.PP
.SH SEE ALSO
Bgee
.SH FILES
.PP
Erica.dll
.PP
