.\" man page create by R# package system.
.TH BGEE 1 2000-1月 "make_matrix" "make_matrix"
.SH NAME
make_matrix \- Make gene expression matrix from the bgee expression calls
.SH SYNOPSIS
\fImake_matrix(\fBbgee\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Make gene expression matrix from the bgee expression calls
.PP
.SH OPTIONS
.PP
\fBbgee\fB \fR\- a stream of the bgee gene expression calls which is parsed from the \fBBgee::parseTsv\fR function.. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
Bgee
.SH FILES
.PP
Erica.dll
.PP
