.\" man page create by R# package system.
.TH BGEE 1 2000-Jan "metabolomicsMapping" "metabolomicsMapping"
.SH NAME
metabolomicsMapping \- 
.SH SYNOPSIS
\fImetabolomicsMapping(\fBuniprot\fR as <generic> pipeline, 
\fBgeneExpressions\fR as <generic> Background, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
Bgee
.SH FILES
.PP
Erica.dll
.PP
