.\" man page create by R# package system.
.TH BGEE 1 2000-01-01 "parseTsv" "parseTsv"
.SH NAME
parseTsv \- 
.SH SYNOPSIS
\fIparseTsv(\fBfile\fR as string, 
\fBadvance\fR as boolean = FALSE, 
\fBquality\fR as string = "*", 
\fBpip_stream\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
Bgee
.SH FILES
.PP
Erica.dll
.PP
