.\" man page create by R# package system.
.TH BGEE 1 2000-1月 "parseTsv" "parseTsv"
.SH NAME
parseTsv \- parse the bgee tsv table file for load the gene expression ranking data
.SH SYNOPSIS
\fIparseTsv(\fBfile\fR as string, 
\fBadvance\fR as boolean = FALSE, 
\fBquality\fR as string = "*", 
\fBpip_stream\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
parse the bgee tsv table file for load the gene expression ranking data
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBadvance\fB \fR\- -. 
.PP
.PP
\fBquality\fB \fR\- -. 
.PP
.PP
\fBpip_stream\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
Bgee
.SH FILES
.PP
Erica.dll
.PP
