.\" man page create by R# package system.
.TH BGEE 1 2000-01-01 "tissue_background" "tissue_background"
.SH NAME
tissue_background \- create tissue and cell background based on bgee database
.SH SYNOPSIS
\fItissue_background(\fBbgee\fR as <generic> AdvancedCalls[], 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create tissue and cell background based on bgee database
.PP
.SH OPTIONS
.PP
\fBbgee\fB \fR\- -. 
.PP
.SH SEE ALSO
Bgee
.SH FILES
.PP
Erica.dll
.PP
