.\" man page create by R# package system.
.TH BGEE 1 2000-Jan "write.backgroundPack" "write.backgroundPack"
.SH NAME
write.backgroundPack \- 
.SH SYNOPSIS
\fIwrite.backgroundPack(\fBbackground\fR as any, 
\fBfile\fR as string, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
Bgee
.SH FILES
.PP
Erica.dll
.PP
