.\" man page create by R# package system.
.TH STDATA 1 2000-1月 "as.STRaid" "as.STRaid"
.SH NAME
as.STRaid \- combine the expression matrix with the spatial spot information
.SH SYNOPSIS
\fIas.STRaid(\fBh5Matrix\fR as <generic> Matrix, 
\fBspots\fR as <generic> SpatialSpot[]);\fR
.SH DESCRIPTION
.PP
combine the expression matrix with the spatial spot information
.PP
.SH OPTIONS
.PP
\fBh5Matrix\fB \fR\- the spatial expression matrix object. 
.PP
.PP
\fBspots\fB \fR\- the spatial spot information. 
.PP
.SH SEE ALSO
STdata
.SH FILES
.PP
Erica.dll
.PP
