.\" man page create by R# package system.
.TH STDATA 1 2000-01-01 "read.ST_spacerangerH5Matrix" "read.ST_spacerangerH5Matrix"
.SH NAME
read.ST_spacerangerH5Matrix \- load the raw expression matrix which is associated
.SH SYNOPSIS
\fIread.ST_spacerangerH5Matrix(\fBh5ad\fR as string);\fR
.SH DESCRIPTION
.PP
load the raw expression matrix which is associated
 with the barcode
.PP
.SH OPTIONS
.PP
\fBh5ad\fB \fR\- -. 
.PP
.SH VALUE
.PP
the result matrix object in format of sample id of the 
 result matrix is the gene id and the row id in matrix is 
 actually the spot xy data tag or the barcoede data
.PP
.SH DETAILS
.PP
the expressin data just associated with the barcode, 
 no spot spatial information.
.PP
.SH SEE ALSO
STdata
.SH FILES
.PP
Erica.dll
.PP
