.\" man page create by R# package system.
.TH STDATA 1 2000-Jan "read.spatial_spots" "read.spatial_spots"
.SH NAME
read.spatial_spots \- load the spatial mapping data of the spot barcode
.SH SYNOPSIS
\fIread.spatial_spots(\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
load the spatial mapping data of the spot barcode 
 associated with the spot spaital information
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.SH SEE ALSO
STdata
.SH FILES
.PP
Erica.dll
.PP
