.\" man page create by R# package system.
.TH STDATA 1 2000-01-01 "sampling" "sampling"
.SH NAME
sampling \- 
.SH SYNOPSIS
\fIsampling(\fBmatrix\fR as <generic> Matrix, 
\fBnsamples\fR as integer = 32);\fR
.SH OPTIONS
.PP
\fBmatrix\fB \fR\- 
 should be a transposed matrix of the output from \fBas.STmatrix\fR. 
. 
.PP
.PP
\fBnsamples\fB \fR\- -. 
.PP
.SH SEE ALSO
STdata
.SH FILES
.PP
Erica.dll
.PP
