.\" man page create by R# package system.
.TH ST-IMAGING 1 2000-Jan "as.STrender" "as.STrender"
.SH NAME
as.STrender \- 
.SH SYNOPSIS
\fIas.STrender(\fBraw\fR as <generic> Matrix, 
\fBspots\fR as <generic> SpatialSpot[]);\fR
.SH OPTIONS
.PP
\fBraw\fB \fR\- 
 the sample id should be the barcodes, and the row id is the gene id
. 
.PP
.PP
\fBspots\fB \fR\- -. 
.PP
.SH SEE ALSO
st-imaging
.SH FILES
.PP
Erica.dll
.PP
