.\" man page create by R# package system.
.TH ST-IMAGING 1 2000-Jan "gene_layer" "gene_layer"
.SH NAME
gene_layer \- get gene layer raw data
.SH SYNOPSIS
\fIgene_layer(\fBimaging\fR as <generic> Render, 
\fBgeneId\fR as string);\fR
.SH DESCRIPTION
.PP
get gene layer raw data
.PP
.SH OPTIONS
.PP
\fBimaging\fB \fR\- -. 
.PP
.PP
\fBgeneId\fB \fR\- -. 
.PP
.SH SEE ALSO
st-imaging
.SH FILES
.PP
Erica.dll
.PP
