.\" man page create by R# package system.
.TH ST-IMAGING 1 2000-01-01 "imaging" "imaging"
.SH NAME
imaging \- do imaging render of a specific gene expression layer
.SH SYNOPSIS
\fIimaging(\fBrender\fR as <generic> Render, 
\fBgeneId\fR as string);\fR
.SH DESCRIPTION
.PP
do imaging render of a specific gene expression layer
.PP
.SH OPTIONS
.PP
\fBrender\fB \fR\- -. 
.PP
.PP
\fBgeneId\fB \fR\- -. 
.PP
.SH SEE ALSO
st-imaging
.SH FILES
.PP
Erica.dll
.PP
