.\" man page create by R# package system.
.TH ST-IMAGING 1 2000-1月 "new_render" "new_render"
.SH NAME
new_render \- 
.SH SYNOPSIS
\fInew_render(\fBh5ad\fR as <generic> AnnData);\fR
.SH OPTIONS
.PP
\fBraw\fB \fR\- 
 the sample id should be the barcodes, and the row id is the gene id
. 
.PP
.PP
\fBspots\fB \fR\- -. 
.PP
.SH SEE ALSO
st-imaging
.SH FILES
.PP
Erica.dll
.PP
