.\" man page create by R# package system.
.TH ST-IMAGING 1 2000-Jan "plot_spots" "plot_spots"
.SH NAME
plot_spots \- 
.SH SYNOPSIS
\fIplot_spots(\fBspots\fR as <generic> SpatialSpot[], 
\fBmatrix\fR as any, 
\fBgeneId\fR as string, 
\fBsize\fR as any = "3000,3000", 
\fBspot_radius\fR as double = 13, 
\fBcolorMaps\fR as <integer> ScalerPalette = [Jet|Autumn|Hot|Spring|plasma|cividis|turbo], 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
st-imaging
.SH FILES
.PP
Erica.dll
.PP
