.\" man page create by R# package system.
.TH ST-IMAGING 1 2000-1月 "spot_heatmap" "spot_heatmap"
.SH NAME
spot_heatmap \- 
.SH SYNOPSIS
\fIspot_heatmap(\fBspots\fR as <generic> PixelData[], 
\fBsize\fR as any = "3000,3000", 
\fBcolorMaps\fR as <integer> ScalerPalette = [turbo], 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
st-imaging
.SH FILES
.PP
Erica.dll
.PP
