.\" man page create by R# package system.
.TH SINGLECELL 1 2000-Jan "dzi_unmix" "dzi_unmix"
.SH NAME
dzi_unmix \- 
.SH SYNOPSIS
\fIdzi_unmix(\fBdzi\fR as <generic> DziImage, 
\fBlevel\fR as integer, 
\fBdir\fR as <generic> IFileSystemEnvironment, 
\fBIHC_antibody\fR as list, 
\fBexport_dir\fR as string);\fR
.SH SEE ALSO
singleCell
.SH FILES
.PP
Erica.dll
.PP
