.\" man page create by R# package system.
.TH SINGLECELL 1 2000-Jan "HE_cells" "HE_cells"
.SH NAME
HE_cells \- scan the cells from a given HE image
.SH SYNOPSIS
\fIHE_cells(\fBHEstain\fR as any, 
\fBis_binarized\fR as boolean = FALSE, 
\fBflip\fR as boolean = FALSE, 
\fBostu_factor\fR as double = 0.7, 
\fBoffset\fR as any = \fB<NULL>\fR, 
\fBnoise\fR as double = 0.25, 
\fBmoran_knn\fR as integer = 32, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
scan the cells from a given HE image
.PP
.SH OPTIONS
.PP
\fBHEstain\fB \fR\- 
 the HE image
. 
.PP
.PP
\fBis_binarized\fB \fR\- -. 
.PP
.PP
\fBflip\fB \fR\- -. 
.PP
.PP
\fBostu_factor\fB \fR\- -. 
.PP
.PP
\fBoffset\fB \fR\- -. 
.PP
.PP
\fBnoise\fB \fR\- -. 
.PP
.PP
\fBmoran_knn\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
singleCell
.SH FILES
.PP
Erica.dll
.PP
