.\" man page create by R# package system.
.TH SINGLECELL 1 2000-Jan "HE_cells" "HE_cells"
.SH NAME
HE_cells \- 
.SH SYNOPSIS
\fIHE_cells(\fBHEstain\fR as any, 
\fBis_binarized\fR as boolean = FALSE, 
\fBflip\fR as boolean = FALSE, 
\fBostu_factor\fR as double = 0.7, 
\fBoffset\fR as any = \fB<NULL>\fR, 
\fBnoise\fR as double = 0.25, 
\fBmoran_knn\fR as integer = 32, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
singleCell
.SH FILES
.PP
Erica.dll
.PP
