.\" man page create by R# package system.
.TH SINGLECELL 1 2000-1月 "HTS_matrix" "HTS_matrix"
.SH NAME
HTS_matrix \- extract the raw expression data matrix from the h5ad object
.SH SYNOPSIS
\fIHTS_matrix(\fBh5ad\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
extract the raw expression data matrix from the h5ad object
.PP
.SH OPTIONS
.PP
\fBh5ad\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
singleCell
.SH FILES
.PP
Erica.dll
.PP
