.\" man page create by R# package system.
.TH SINGLECELL 1 2000-Jan "hungarian_assignment" "hungarian_assignment"
.SH NAME
hungarian_assignment \- 
.SH SYNOPSIS
\fIhungarian_assignment(\fBphase1\fR as <generic> CellScan[], 
\fBphase2\fR as <generic> CellScan[]);\fR
.SH SEE ALSO
singleCell
.SH FILES
.PP
Erica.dll
.PP
