.\" man page create by R# package system.
.TH SINGLECELL 1 2000-Jan "ihc_unmixing" "ihc_unmixing"
.SH NAME
ihc_unmixing \- Debug test used only
.SH SYNOPSIS
\fIihc_unmixing(\fBpixel\fR as any, 
\fBtype\fR as any = ["ihc1","ihc2"], 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Debug test used only
.PP
.SH OPTIONS
.PP
\fBpixel\fB \fR\- [r,g,b] color value, in range [0,1]. 
.PP
.PP
\fBtype\fB \fR\- -. 
.PP
.SH SEE ALSO
singleCell
.SH FILES
.PP
Erica.dll
.PP
