.\" man page create by R# package system.
.TH SINGLECELL 1 2000-Jan "parse_dziImage" "parse_dziImage"
.SH NAME
parse_dziImage \- Parse the dzi image metadata from a given xml document data
.SH SYNOPSIS
\fIparse_dziImage(\fBxml\fR as string);\fR
.SH DESCRIPTION
.PP
Parse the dzi image metadata from a given xml document data
.PP
.SH OPTIONS
.PP
\fBxml\fB \fR\- -. 
.PP
.SH SEE ALSO
singleCell
.SH FILES
.PP
Erica.dll
.PP
