.\" man page create by R# package system.
.TH SINGLECELL 1 2000-Jan "pca_annotation" "pca_annotation"
.SH NAME
pca_annotation \- Extract the PCA matrix from h5ad
.SH SYNOPSIS
\fIpca_annotation(\fBh5ad\fR as <generic> AnnData);\fR
.SH DESCRIPTION
.PP
Extract the PCA matrix from h5ad
.PP
.SH OPTIONS
.PP
\fBh5ad\fB \fR\- -. 
.PP
.SH SEE ALSO
singleCell
.SH FILES
.PP
Erica.dll
.PP
