.\" man page create by R# package system.
.TH SINGLECELL 1 2000-Jan "RANSAC_cell_alignment" "RANSAC_cell_alignment"
.SH NAME
RANSAC_cell_alignment \- 
.SH SYNOPSIS
\fIRANSAC_cell_alignment(\fBsliceA\fR as <generic> CellScan[], 
\fBsliceB\fR as <generic> CellScan[], 
\fBiterations\fR as integer = 1000, 
\fBdistance_threshold\fR as double = 0.1);\fR
.SH SEE ALSO
singleCell
.SH FILES
.PP
Erica.dll
.PP
