.\" man page create by R# package system.
.TH SINGLECELL 1 2000-Jan "read.dziImage" "read.dziImage"
.SH NAME
read.dziImage \- read the deepzoom image metadata xml file
.SH SYNOPSIS
\fIread.dziImage(\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
read the deepzoom image metadata xml file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.SH SEE ALSO
singleCell
.SH FILES
.PP
Erica.dll
.PP
