.\" man page create by R# package system.
.TH SINGLECELL 1 2000-Jan "read.h5ad" "read.h5ad"
.SH NAME
read.h5ad \- read h5ad object from a specific hdf5 file
.SH SYNOPSIS
\fIread.h5ad(\fBh5adfile\fR as string, 
\fBloadExpr0\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
read h5ad object from a specific hdf5 file
.PP
.SH OPTIONS
.PP
\fBh5adfile\fB \fR\- -. 
.PP
.PP
\fBloadExpr0\fB \fR\- -. 
.PP
.SH SEE ALSO
singleCell
.SH FILES
.PP
Erica.dll
.PP
