.\" man page create by R# package system.
.TH SINGLECELL 1 2000-Jan "scan.dzi_cells" "scan.dzi_cells"
.SH NAME
scan.dzi_cells \- 
.SH SYNOPSIS
\fIscan.dzi_cells(\fBdzi\fR as <generic> DziImage, 
\fBlevel\fR as integer, 
\fBdir\fR as string, 
\fBostu_factor\fR as double = 0.7, 
\fBnoise\fR as double = 0.25, 
\fBmoran_knn\fR as integer = 32);\fR
.SH SEE ALSO
singleCell
.SH FILES
.PP
Erica.dll
.PP
