.\" man page create by R# package system.
.TH SINGLECELL 1 2000-Jan "scan.dzi_cells" "scan.dzi_cells"
.SH NAME
scan.dzi_cells \- Scan all single cell shapes from the given dzi slide data
.SH SYNOPSIS
\fIscan.dzi_cells(\fBdzi\fR as <generic> DziImage, 
\fBlevel\fR as integer, 
\fBdir\fR as <generic> IFileSystemEnvironment, 
\fBostu_factor\fR as double = 0.7, 
\fBnoise\fR as double = 0.25, 
\fBmoran_knn\fR as integer = 32, 
\fBflip\fR as boolean = FALSE, 
\fBsplit_blocks\fR as boolean = FALSE, 
\fBsplit_IHC1_channels\fR as boolean = FALSE, 
\fBsplit_IHC2_channels\fR as boolean = FALSE);\fR
.SH DESCRIPTION
.PP
Scan all single cell shapes from the given dzi slide data
.PP
.SH OPTIONS
.PP
\fBdzi\fB \fR\- metadata of the dzi image. 
.PP
.PP
\fBlevel\fB \fR\- usually be the max zoom level. 
.PP
.PP
\fBdir\fB \fR\- 
 A directory path that contains the image files in current **`level`**.
. 
.PP
.PP
\fBostu_factor\fB \fR\- -. 
.PP
.PP
\fBnoise\fB \fR\- 
 quantile level for filter the polygon shape points. all cell shapes which has its
 shape points less than this quantile level will be treated as noise
. 
.PP
.PP
\fBmoran_knn\fB \fR\- -. 
.PP
.PP
\fBsplit_blocks\fB \fR\- -. 
.PP
.SH VALUE
.PP
if scanning of the IHC1 channels, then this function will returns a tuple list that contains
 the rgb channels single cell detections result of the IHC1 image.
 if scanning of the IHC2 channels, then this function will returns a tuple list that contains
 the cmyk channels single cell detection result of the IHC2 image.
.PP
.SH SEE ALSO
singleCell
.SH FILES
.PP
Erica.dll
.PP
