.\" man page create by R# package system.
.TH SINGLECELL 1 2000-Jan "spatialMap" "spatialMap"
.SH NAME
spatialMap \- export the spatial maps data
.SH SYNOPSIS
\fIspatialMap(\fBh5ad\fR as <generic> AnnData, 
\fBuseCellAnnotation\fR as <generic> Boolean = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
export the spatial maps data
.PP
.SH OPTIONS
.PP
\fBh5ad\fB \fR\- -. 
.PP
.PP
\fBuseCellAnnotation\fB \fR\- -. 
.PP
.SH EXAMPLES
.PP
let stRaid = read.h5ad("/path/to/expr_mat.h5ad");
 let spatial = spatialMap(stRaid);
 
 str(spatial);
.PP
.SH SEE ALSO
singleCell
.SH FILES
.PP
Erica.dll
.PP
