.\" man page create by R# package system.
.TH SINGLECELL 1 2000-1月 "spatial_annotations" "spatial_annotations"
.SH NAME
spatial_annotations \- Create spatial annotations data set for each spot data
.SH SYNOPSIS
\fIspatial_annotations(\fBx\fR as any, 
\fBy\fR as any, 
\fBlabel\fR as any, 
\fBcolors\fR as any = "paper", 
\fBbarcode\fR as any = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Create spatial annotations data set for each spot data
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- X of the spot dataset, a numeric vector. 
.PP
.PP
\fBy\fB \fR\- Y of the spot dataset, a numeric vector. 
.PP
.PP
\fBlabel\fB \fR\- A character vector that assign the class label of each
 spatial spot, the vector size of this parameter must be equals to the 
 vector size of x and y.. 
.PP
.PP
\fBcolors\fB \fR\- A character value of the spatial class color 
 palette name or a vector of color code character for assign each 
 spatial spot.. 
.PP
.PP
\fBbarcode\fB \fR\- 
 the raw reference barcode to the spots
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
singleCell
.SH FILES
.PP
Erica.dll
.PP
