.\" man page create by R# package system.
.TH SINGLECELL 1 2000-Jan "write.cells_bson" "write.cells_bson"
.SH NAME
write.cells_bson \- write the cell matrix data into a bson file
.SH SYNOPSIS
\fIwrite.cells_bson(\fBcells\fR as <generic> CellScan[], 
\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
write the cell matrix data into a bson file
.PP
.SH OPTIONS
.PP
\fBcells\fB \fR\- a vector of the cell objects. 
.PP
.PP
\fBfile\fB \fR\- file path to the bson file for save the cell matrix data. 
.PP
.SH SEE ALSO
singleCell
.SH FILES
.PP
Erica.dll
.PP
