.\" man page create by R# package system.
.TH PHENOGRAPH 1 2000-1月 "cluster_colors" "cluster_colors"
.SH NAME
cluster_colors \- set cluster colors of the phenograph result
.SH SYNOPSIS
\fIcluster_colors(\fBg\fR as <generic> NetworkGraph, 
\fBcolorSet\fR as any = "viridis:turbo", 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
set cluster colors of the phenograph result
.PP
.SH OPTIONS
.PP
\fBg\fB \fR\- -. 
.PP
.PP
\fBcolorSet\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
phenograph
.SH FILES
.PP
Erica.dll
.PP
