.\" man page create by R# package system.
.TH PHENOGRAPH 1 2000-Jan "correlation_graph" "correlation_graph"
.SH NAME
correlation_graph \- 
.SH SYNOPSIS
\fIcorrelation_graph(\fBx\fR as <generic> Matrix, 
\fBy\fR as <generic> Matrix, 
\fBeq\fR as double = 0.85);\fR
.SH SEE ALSO
phenograph
.SH FILES
.PP
Erica.dll
.PP
