.\" man page create by R# package system.
.TH PHENOGRAPH 1 2000-1月 "neighbor_community" "neighbor_community"
.SH NAME
neighbor_community \- build phenograph from knn search result
.SH SYNOPSIS
\fIneighbor_community(\fBneighborMatrix\fR as any, 
\fBlink_cutoff\fR as double = 0, 
\fBsubcomponents_filter\fR as integer = 0, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
build phenograph from knn search result
.PP
.SH OPTIONS
.PP
\fBneighborMatrix\fB \fR\- should be a collection of the KNN search result: @\fBT:Microsoft.VisualBasic.Data.GraphTheory.KdTree.ApproximateNearNeighbor.KNeighbors\fR.. 
.PP
.PP
\fBlink_cutoff\fB \fR\- -. 
.PP
.PP
\fBsubcomponents_filter\fB \fR\- -. 
.PP
.SH SEE ALSO
phenograph
.SH FILES
.PP
Erica.dll
.PP
