.\" man page create by R# package system.
.TH PHENOGRAPH 1 2000-Jan "phenograph" "phenograph"
.SH NAME
phenograph \- Run PhenoGraph algorithm
.SH SYNOPSIS
\fIphenograph(\fBx\fR as <generic> Matrix, 
\fBy\fR as <generic> Matrix = \fB<NULL>\fR, 
\fBk\fR as integer = 30, 
\fBlink_cutoff\fR as double = 0, 
\fBknn_cutoff\fR as double = 0, 
\fBscore\fR as <generic> ScoreMetric = \fB<NULL>\fR, 
\fBsubcomponents_filter\fR as integer = 0, 
\fBknn2\fR as integer = 16, 
\fBjoint_cutoff\fR as double = 0, 
\fBn_threads\fR as integer = 32, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Run PhenoGraph algorithm
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- This parameter should be an expression matrix data object. 
.PP
.PP
\fBk\fB \fR\- The KNN parameter for the phenograph analysis on the input matrix **`x`**. 
.PP
.PP
\fBlink_cutoff\fB \fR\- -. 
.PP
.PP
\fBsubcomponents_filter\fB \fR\- 
 removes small subnetwork
. 
.PP
.SH SEE ALSO
phenograph
.SH FILES
.PP
Erica.dll
.PP
