.\" man page create by R# package system.
.TH PHENOGRAPH 1 2000-01-01 "score_metric" "score_metric"
.SH NAME
score_metric \- create a new score metric for KNN method in phenograph algorithm
.SH SYNOPSIS
\fIscore_metric(\fBmetric\fR as any = ["cosine","jaccard","pearson"], 
\fBenv\fR as <generic> Environment = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
create a new score metric for KNN method in phenograph algorithm
.PP
.SH OPTIONS
.PP
\fBmetric\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
phenograph
.SH FILES
.PP
Erica.dll
.PP
