.\" man page create by R# package system.
.TH PHENOGRAPH 1 2000-Jan "score_metric" "score_metric"
.SH NAME
score_metric \- create a new score metric for KNN method in phenograph algorithm
.SH SYNOPSIS
\fIscore_metric(\fBmetric\fR as any = ["cosine","jaccard","pearson","spearman"], 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create a new score metric for KNN method in phenograph algorithm
.PP
.SH OPTIONS
.PP
\fBmetric\fB \fR\- 
 1. cosine: the cosine similarity score
 2. jaccard: the jaccard similarity score
 3. pearson: the pearson correlation score(WGCNA co-expression weight actually)
 4. spearman: the spearman correlation score(WGCNA spearman weight score)
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
phenograph
.SH FILES
.PP
Erica.dll
.PP
