.\" man page create by R# package system.
.TH PHENOGRAPH 1 2000-1月 "setInteraction" "setInteraction"
.SH NAME
setInteraction \- 
.SH SYNOPSIS
\fIsetInteraction(\fBg\fR as <generic> NetworkGraph, 
\fBgeneIds\fR as string, 
\fBmetaboliteIds\fR as string);\fR
.SH SEE ALSO
phenograph
.SH FILES
.PP
Erica.dll
.PP
