.\" man page create by R# package system.
.TH PHENOGRAPH 1 2000-Jan "slice_matrix" "slice_matrix"
.SH NAME
slice_matrix \- 
.SH SYNOPSIS
\fIslice_matrix(\fBx\fR as <generic> Matrix, 
\fBmapping\fR as list, 
\fBaxis\fR as any = ["x","y"], 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBmapping\fB \fR\- 
 the spatial spot mapping result which is evaluated from the \fBcorrelation_graph\fR function.
. 
.PP
.PP
\fBaxis\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
phenograph
.SH FILES
.PP
Erica.dll
.PP
