.\" man page create by R# package system.
.TH STDECONVOLVE 1 2000-Jan "fitLDA" "fitLDA"
.SH NAME
fitLDA \- run LDA modelling
.SH SYNOPSIS
\fIfitLDA(\fBspatialDoc\fR as <generic> STCorpus, 
\fBk\fR as integer, 
\fBalpha\fR as double = 2, 
\fBbeta\fR as double = 0.5, 
\fBloops\fR as integer = 200, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
run LDA modelling
.PP
.SH OPTIONS
.PP
\fBspatialDoc\fB \fR\- -. 
.PP
.PP
\fBk\fB \fR\- -. 
.PP
.PP
\fBalpha#\fB \fR\- -. 
.PP
.PP
\fBbeta#\fB \fR\- -. 
.PP
.SH DETAILS
.PP
Fit the optimal number of cell-types K for the LDA model
.PP
.SH SEE ALSO
STdeconvolve
.SH FILES
.PP
Erica.dll
.PP
