.\" man page create by R# package system.
.TH STDECONVOLVE 1 2000-Jan "singlecells" "singlecells"
.SH NAME
singlecells \- get the single cell expression matrix
.SH SYNOPSIS
\fIsinglecells(\fBdeconv\fR as <generic> Deconvolve, 
\fBexpr\fR as <generic> Matrix, 
\fBprefix\fR as string = "class");\fR
.SH DESCRIPTION
.PP
get the single cell expression matrix
.PP
.SH OPTIONS
.PP
\fBdeconv\fB \fR\- -. 
.PP
.PP
\fBexpr\fB \fR\- -. 
.PP
.SH SEE ALSO
STdeconvolve
.SH FILES
.PP
Erica.dll
.PP
