.\" man page create by R# package system.
.TH STDECONVOLVE 1 2000-Jan "STCorpus" "STCorpus"
.SH NAME
STCorpus \- Create document vector for run LDA mdelling
.SH SYNOPSIS
\fISTCorpus(\fBmatrix\fR as <generic> Matrix, 
\fBmin\fR as double = 0.05, 
\fBmax\fR as double = 0.95, 
\fBunify\fR as integer = 10, 
\fBlogNorm\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
Create document vector for run LDA mdelling
.PP
.SH OPTIONS
.PP
\fBmatrix\fB \fR\- 
 row is pixels and column is gene features. each 
 pixel row is a document sample in LDA model
. 
.PP
.PP
\fBmin\fB \fR\- -. 
.PP
.PP
\fBmax\fB \fR\- -. 
.PP
.PP
\fBunify\fB \fR\- -. 
.PP
.PP
\fBlogNorm\fB \fR\- -. 
.PP
.SH VALUE
.PP
document model for run LDA modelling
.PP
.SH SEE ALSO
STdeconvolve
.SH FILES
.PP
Erica.dll
.PP
