.\" man page create by R# package system.
.TH GRN 1 2000-1月 "learn_grn" "learn_grn"
.SH NAME
learn_grn \- 
.SH SYNOPSIS
\fIlearn_grn(\fBvelocity_prior\fR as <generic> DBNPreprocessOutput, 
\fBprior\fR as <generic> PriorNetwork, 
\fBmaxIters\fR as integer = 500);\fR
.SH SEE ALSO
GRN
.SH FILES
.PP
Erica.dll
.PP
