.\" man page create by R# package system.
.TH GRN 1 2000-1月 "time_series" "time_series"
.SH NAME
time_series \- get time series expression matrix from processed DBN sample output, for GRN learning
.SH SYNOPSIS
\fItime_series(\fBx\fR as <generic> DBNPreprocessOutput);\fR
.SH DESCRIPTION
.PP
get time series expression matrix from processed DBN sample output, for GRN learning
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.SH SEE ALSO
GRN
.SH FILES
.PP
Erica.dll
.PP
