.\" man page create by R# package system.
.TH MONOCLE3 1 2000-1月 "new" "new"
.SH NAME
new \- 
.SH SYNOPSIS
\fInew(\fBnumPCA\fR as integer = 10, 
\fBumapDim\fR as integer = 3, 
\fBknnK\fR as integer = 15, 
\fBresolution\fR as double = 1, 
\fBuseLeiden\fR as boolean = FALSE, 
\fBuseCache\fR as boolean = TRUE, 
\fBoverwriteCache\fR as boolean = FALSE, 
\fBcacheDir\fR as string = "./cache", 
\fBpseudoVeloEnabled\fR as boolean = TRUE, 
\fBpseudoVeloWindow\fR as integer = 2, 
\fBpseudoVeloSpan\fR as double = 0.3, 
\fBuseVelocityProjection\fR as boolean = TRUE, 
\fBnumHVGenes\fR as integer = 3000);\fR
.SH SEE ALSO
monocle3
.SH FILES
.PP
Erica.dll
.PP
